title: Luis Palacios
description: Luis Palacios. A paper, two systems, and a place for notes.
baseurl: ""
url: "https://luisfpal.github.io"

markdown: kramdown
kramdown:
  input: GFM

exclude:
  - "Git Stash Usage Explained.md"
  - README.md
